TESTING = True

TARGET_MARKING = (1, 2, 6, 9)

IMG_WIDTH = 260
IMG_HEIGHT = 340

IMG_SIZE = (IMG_WIDTH, IMG_HEIGHT)

CARRIAGE_WIDTH = 10
CARRIAGE_HEIGHT = 340

CARRIAGE_SIZE = (CARRIAGE_WIDTH, CARRIAGE_HEIGHT)