TESTING = True
TEST_IMGS = r"res\NoMove"

TARGET_MATRIX_MARKING = (2, 9, 1, 6)
TARGET_STRIPES_MARKING = (5, 7, 2)

IMG_WIDTH = 260
IMG_HEIGHT = 340

IMG_SIZE = (IMG_WIDTH, IMG_HEIGHT)

CARRIAGE_WIDTH = 10
CARRIAGE_HEIGHT = 340

CARRIAGE_SIZE = (CARRIAGE_WIDTH, CARRIAGE_HEIGHT)