"""Config file of this project"""

import numpy as np
from io_client import InputType


INPUT_MODE = InputType.IMAGE_FOLDER
DEBUG = True

IMG_W = 640
IMG_H = 480
IMG_SHAPE = (IMG_W, IMG_H)

CAR_MAX_ANGLE: float = 45
CAR_MAX_SPEED: int = 255
CAR_MIN_SPEED: int = 100
MAX_DEVIATION: float = 1
PIXEL_TO_CM_RATIO: float = 0.05

CROSSROAD_STOP_DIST: float = 6.5
CROSSROAD_SLOW_DOWN_DIST: float = 15
CROSSROAD_STOP_TIME: float = 1.0
CROSSROAD_SPEED_LIMIT: float = 50

PEDESTRIAN_STOP_DISTANCE: float = 10
PEDESTRIAN_SLOW_DOWN_DISTANCE: float = 20
PEDESTRIAN_SPEED_LIMIT: float = 50

CMD_BUFF_LEN = 2

UDP_HOST = "0.0.0.0"
UDP_PORT = 5000
# TCP_HOST = "192.168.0.12"
TCP_HOST = "192.168.17.46"
TCP_PORT = 5001

IMG_SOURCE_FOLDER_PATH = r'C:\Users\fun1h\Documents\AVT-NTO\EyeCar\images'
MODEL_FOLDER_PATH = r''
